from __future__ import annotations

APP_TITLE = """E2E BeRTA Renderer Tester
Project: SONICOM (GA No. 101017743)
Developed by: 3DI-DIANA Group, (c) University of Malaga (UMA)
Website: www.sonicom.eu
····"""

DEFAULT_WINDOWS_BERTA_EXECUTABLE = (
    r"C:\Program Files\University of Malaga\BeRTA-Renderer App\BeRTA-Renderer.exe"
)

DEFAULT_MACOS_BERTA_EXECUTABLE = (
    "/Applications/BeRTA-Renderer.app/Contents/MacOS/BeRTA-Renderer"
)

BERTA_EXECUTABLE_ENV_VAR = "BERTA_RENDERER_EXECUTABLE"

# OSC defaults. Override these with environment variables if your BeRTA settings
# file uses different ports.
BERTA_OSC_IP_ENV_VAR = "BERTA_OSC_IP"
BERTA_OSC_PORT_ENV_VAR = "BERTA_OSC_PORT"
TESTER_OSC_IP_ENV_VAR = "TESTER_OSC_IP"
TESTER_OSC_PORT_ENV_VAR = "TESTER_OSC_PORT"
OSC_STARTUP_TIMEOUT_ENV_VAR = "BERTA_OSC_STARTUP_TIMEOUT"
OSC_CONNECT_RETRY_WAIT_SECONDS_ENV_VAR = "BERTA_OSC_CONNECT_RETRY_WAIT_SECONDS"
OSC_CONNECT_MAX_ATTEMPTS_ENV_VAR = "BERTA_OSC_CONNECT_MAX_ATTEMPTS"

DEFAULT_BERTA_OSC_IP = "127.0.0.1"
DEFAULT_BERTA_OSC_PORT = 10017
DEFAULT_TESTER_OSC_IP = "127.0.0.1"
DEFAULT_TESTER_OSC_PORT = 10011
DEFAULT_OSC_STARTUP_TIMEOUT_SECONDS = 15.0
DEFAULT_OSC_CONNECT_RETRY_WAIT_SECONDS = 2.0
DEFAULT_OSC_CONNECT_MAX_ATTEMPTS = 3
